server:
  port: 8080

spring:
  application:
    name: retail-demo-spring
  profiles:
    active: old-client  # Default to old-client implementation
    # Alternative: new-client for enhanced implementation

# Aerospike configuration
aerospike:
  host: localhost
  port: 3000

# Logging configuration
logging:
  level:
    com.aerospike: DEBUG
    root: INFO 